### ISSUE TITLE
matcaffe interface problem

### ISSUE THREAD

**Issue by doonny** [pmgysel/alexnet-forwardpath#1]
Hello, I am using matcaffe interface to extract the weights, but there are noly functions like caffe.Net (), caffe.Solver() to use, it seems that caffe('arg1', 'arg2') is not supported.

Do you know any other ways to extract the weights ?  Thanks a lot ~~

**Comment by pmgysel** [comment]
Hi Donny

Good question. My guess is the Matcaffe function caffe(...) doesn't exist anymore. A detailed explanation for extracting weights can be found here: http://caffe.berkeleyvision.org/tutorial/interfaces.html. Take a look at section "Create a network and access its layers and blobs".

I'm traveling right now, but I'll update the Readme file as soon as possible. Let me know if that solves your issue.

**Comment by doonny** [comment]
Hi Philipp,

```
 Thanks a lot for your reply. I will read the instructions first, 
```

and try to use the new api.

```
 Dong Wang
```

在 2016/1/24 5:05, Philipp Gysel 写道:

**Comment by doonny** [comment]
The following scripts can extract the weights, in case anyone needed:

caffe.set_mode_cpu();
model = './models/bvlc_reference_caffenet/deploy.prototxt';
weights = './models/bvlc_reference_caffenet.caffemodel';
net = caffe.Net(model, weights, 'test');

netparams = {{net.params('conv1',1).get_data(),net.params('conv1',2).get_data()}, ...
            {net.params('conv2',1).get_data(),net.params('conv2',2).get_data()}, ...
            {net.params('conv3',1).get_data(),net.params('conv3',2).get_data()}, ...
            {net.params('conv4',1).get_data(),net.params('conv4',2).get_data()}, ...
            {net.params('conv5',1).get_data(),net.params('conv5',2).get_data()}, ...
            {net.params('fc6',1).get_data(),net.params('fc6',2).get_data()}, ...
            {net.params('fc7',1).get_data(),net.params('fc7',2).get_data()}, ...
            {net.params('fc8',1).get_data(),net.params('fc8',2).get_data()}};

save('weights.mat',netparams);

**Comment by pmgysel** [comment]
Thanks a lot for pointing out the issue with the weight extraction! I provide a download link to the pretrained weights. The readme is updated.
